# @package _global_

# Multi-objective optimization: on PA, RA and CA (Proportion of Automatization + Refutation/Confirmation Accuracy)
# Run with something like:
# python run.py -m task=tune hparams_search=thresholds_3_objectives hydra.sweeper.n_jobs=3 hydra.sweeper.n_trials=100 print_config=false

print_config: false

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: nsgaii
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: thresholds_multiobjective
    n_jobs: 5
    direction: [maximize, maximize, maximize]

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.NSGAIISampler
      seed: 12345

    # # FULL RANGE
    n_trials: 100
    search_space:
      inspection.min_confidence_confirmation:
        type: float
        low: 0.0
        high: 1.0
      inspection.min_confidence_refutation:
        type: float
        low: 0.0
        high: 1.0
      inspection.min_frac_confirmation:
        type: float
        low: 0.0
        high: 1.0
      inspection.min_frac_refutation:
        type: float
        low: 0.0
        high: 1.0

    # # NARROW RANGE - based on first results of full range HPO
    # n_trials: 40
    # search_space:
    #   inspection.min_confidence_confirmation:
    #     type: float
    #     low: 0.10
    #     high: 0.8
    #   inspection.min_confidence_refutation:
    #     type: float
    #     low: 0.7
    #     high: 0.9
    #   inspection.min_frac_confirmation:
    #     type: float
    #     low: 0.7
    #     high: 0.95
    #   inspection.min_frac_refutation:
    #     type: float
    #     low: 0.45
    #     high: 0.75

