_target_: src.models.model.Model

num_classes: 6

# Architecture defined in sub-configs
neural_net_class_name: ???
neural_net_hparams: ???

# Evaluation metric - partial for triple initi
iou:
  _target_: functools.partial
  _args_:
    - "${get_method:torchmetrics.IoU}"
    - ${model.num_classes}
  absent_score: 1.0

# Optimization

criterion: 
  _target_: torch.nn.CrossEntropyLoss

lr: 0.004566395347136576  # 200-long LR-test-range betw 10^-4 and 3.0

optimizer: 
  _target_: functools.partial
  _args_: 
    - "${get_method:torch.optim.Adam}"
  lr: ${model.lr}

lr_scheduler:
  _target_: functools.partial
  _args_: 
    - ${get_method:torch.optim.lr_scheduler.ReduceLROnPlateau}
  mode: "min"
  factor: 0.5  # halving
  patience: 5  # val epochs
  cooldown: 0  # val epochs

monitor: "val/loss_epoch"