_target_: semantic_val.models.point_net_model.PointNetModel

MLP1_channels: [6, 32, 32]
MLP2_channels: [32, 64, 64]
MLP3_channels: [96, 128, 128, 64, 16, 2] # 64 + 32 = 96
subsampling_size: 10000
lr: 0.001
save_predictions: true
