_target_: semantic_val.models.model.SegmentationModel

save_predictions: true
loss: "CrossEntropyLoss"
lr: 0.01
save_train_predictions_every_n_epoch: ${trainer.check_val_every_n_epoch}

net:
  MLP1_channels: [6, 64, 64]
  MLP2_channels: [64, 256, 512, 1024]
  MLP3_channels: [1088, 512, 256, 64, 4]
  num_classes: 2
  batch_norm: false
  pi_init: 0.05

