defaults:
  - default.yaml

neural_net_class_name: "RandLANet"
neural_net_hparams:
  num_classes: ${model.num_classes}
  d_in: 6  # 3 (xyz) + num of features
  num_neighbors: 16 
  decimation: 4  # divide by decimation for each of the 4 local encoder.
  dropout: 0.5  # Use 0.0 of false to deactivate

# not a package