defaults:
  - default.yaml

_target_: semantic_val.models.model.Model

model_architecture: "randla_net"

net:
  d_in: 6  # 3 + F
  num_classes: 6
  num_neighbors: 16 
  decimation: 4  # divide by decimation for each of the 4 local encoder.