# OPTIMIZATION PARAMETERS
predicted_las_dirpath:  "/path/to/folder/"  # contains .las files
todo: "prepare+optimize+evaluate+update"  # for test data use prepare+evaluate+update
results_output_dir: "/path/to/folder/"  # will contain best optimization trial and (optionnaly) updated las
best_trial_pickle_path: "/path/to/best_trial.pkl"  # To save optimized parameters from Optuna
input_bd_topo_shp: ${oc.env:INPUT_BD_TOPO_SHP_PATH}

study:
  n_trials: 300
  study_name: "auto_precision_recall"
  directions: ["maximize","maximize","maximize"]

sampler_class: optuna.samplers.NSGAIISampler
sampler_kwargs:
  population_size: 30
  mutation_prob: 0.25
  crossover_prob: 0.8
  swapping_prob: 0.5
  seed: 12345
  constraints_func: none  # Created dynamically