# OPTIMIZATION PARAMETERS
predicted_las_dirpath:  "/path/to/folder/"  # contains .las files
update_las: false  # memory intensive -set to true to propagate decisions to las files when optimizing. 
results_output_dir: "/path/to/folder/"  # will contain best optimization trial and (optionnaly) updated las