src_las: "/path/to/input.las"
output_dir: "/path/to/output_dir/"
resume_from_checkpoint: "/path/to/lightning_model.ckpt"
names_of_probas_to_save: ["ground","vegetation","building"]
gpus: 0  # 0 for none, 1 for one, [gpu_id] to specify which gpu to use e.g [1]