src_las: "/path/to/input.las"
output_dir: "/path/to/output_dir/"
resume_from_checkpoint: "/path/to/lightning_model.ckpt"
gpus: 0  # 0 for none, 1 for one, [gpu_id] to specify which gpu to use e.g [1]

probas_to_save: "all"  # override with a list of string matching class names to select specific probas to save

# Relative to how probas are interpolated
# e.g. subtile_overlap=25 to use a sliding window of inference of whihc predictions will be merged.
subtile_overlap: 25
interpolation_k: 10