src_las: "/path/to/input.las"  # Any glob pattern can be used to predict on multiple files.
output_dir: "/path/to/output_dir/"  # Predictions are saved in a new file which shares src_las basename.
ckpt_path: "/path/to/lightning_model.ckpt"  # Checkpoint of trained model.
gpus: 0  # 0 for none, 1 for one, [gpu_id] to specify which gpu to use e.g [1]

# Specifying the ouptut:
# A list of string matching class names to select specific probas to save
# OR keyword "all" to save all probabilities.
# In addition, these dimensions are always created:
# - `PredictedClassification`: predicted classification based on argmax, with classes 
#   specified by dataset_description class dictionary. 
# - entropy`: Shannon entropy of predicted probabilities 
probas_to_save: "all"

# Probas interpolation parameters
# subtile_overlap=25 to use a sliding window of inference of which predictions will be merged.
# This comes with a computing cost as the effective predicted area is multiplied.
subtile_overlap: 0
# Higher interpolation_k to use more context
interpolation_k: 10