src_las: "/path/to/input.las"
output_dir: "/path/to/output_dir/"
resume_from_checkpoint: "/path/to/lightning_model.ckpt"
gpus: 0  # 0 for none, 1 for one, [gpu_id] to specify which gpu to use e.g [1]

names_of_probas_to_save: ${datamodule.dataset_description.names_of_probas_to_save}

# Relative to how probas are interpolated
# e.g. subtile_overlap=40 & interpolation_k=10
subtile_overlap: 0
interpolation_k: 1