
save_preds:
  _target_: semantic_val.callbacks.predictions_callbacks.SavePreds
  save_predictions: false
  save_train_predictions_every_n_step: 1000000

log_code:
  _target_: semantic_val.callbacks.comet_callbacks.LogCode
  code_dir: ${work_dir}/semantic_val

lr_monitor:
  _target_:  pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/iou_epoch" # name of the logged metric which determines when model is improving
  mode: "max" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/iou_epoch" # name of the logged metric which determines when model is improving
  mode: "max" # can be "max" or "min"
  patience: 6 # how many validation epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

