# Override with "none" to deactivate. 

log_code:
  _target_: myria3d.callbacks.comet_callbacks.LogCode
  code_dir: ${work_dir}/myria3d

log_logs_dir:
  _target_: myria3d.callbacks.comet_callbacks.LogLogsPath

lr_monitor:
  _target_:  pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"
  log_momentum: true

# This logs IoU at validation and test time
# Predictions are aggregated and saved at test time in a way coherent with prediction logic.
log_iou_by_class:
  _target_: myria3d.callbacks.logging_callbacks.LogIoUByClass
  classification_dict: ${datamodule.dataset_description.classification_dict}
  interpolator:  # only used at test time
    _target_: myria3d.models.interpolation.Interpolator
    interpolation_k: ${predict.interpolation_k}
    classification_dict: ${datamodule.dataset_description.classification_dict}
    probas_to_save: ${predict.probas_to_save}  # replace by a list of string of class names to select specific probas to save
    output_dir: null # Replace by an output to save resultsduring test

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss_epoch" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: True
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/loss_epoch" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  patience: 6 # how many validation epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement
  
