_target_: lidar_multiclass.datamodules.datamodule.DataModule

# those two paths are specified in configs/config.yaml
input_data_dir: ${oc.env:INPUT_DATA_DIR}
prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

num_workers: 1
batch_size: 32
subsample_size: 12500
subtile_width_meters: 50

augment: false

# By default, do not use the test set unless explicitely required by user.
use_val_data_at_test_time: true

# The class that has a load_las_data class method.
loading_func:
  _target_: lidar_multiclass.datamodules.data_logic.FrenchLidarDataLogic

# Dataset Specific information
defaults:
  - dataset_description: SwissSURFACE3D.yaml
