_target_: lidar_multiclass.datamodules.datamodule.DataModule

prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

num_workers: 1
batch_size: 32
subsample_size: 12500
subtile_width_meters: 50
subtile_overlap: 0  # e.g. 40 - combine with interpolation_k > 1

augment: false

# Dataset Specific information
defaults:
  - dataset_description: SwissSURFACE3D_all_6_classes.yaml
