_target_: lidar_multiclass.datamodules.datamodule.DataModule

prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

num_workers: 1
batch_size: 32
subtile_width_meters: 50
subtile_overlap: ${predict.subtile_overlap}  # Used for test and predict phases only

augment: false

defaults:
  - dataset_description: 20220204_BuildingValidation_and_Ground.yaml
  - subsampler: grid.yaml
