_target_: src.datamodules.datamodule.DataModule

# those two paths are specified in configs/config.yaml
input_data_dir: ${oc.env:INPUT_DATA_DIR}
prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

# classification_dict = {int: name, ...} and MUST be sorted (increasing order). 
classification_dict: {1: "unclassified", 2: "ground", 3: "vegetation", 6: "building", 9: "water", 17: "bridge"}

batch_size: 32

augment: false
subsample_size: 12500
subtile_width_meters: 50

num_workers: 1

# By default, do not use the test set unless explicitely required by user.
use_val_data_at_test_time: true

