_target_: semantic_val.datamodules.datamodule.DataModule

# those two paths are specified in configs/config.yaml
lasfiles_dir: ${lasfiles_dir}
metadata_shapefile: ${metadata_shapefile}
logfile_dir: ${logfile_dir}

batch_size: 32

augment: false
subsample_size: 12500
subtile_width_meters: 50

num_workers: 1

# By default, do not use the test set unless explicitely required by user.
use_val_data_at_test_time: true

