_target_: semantic_val.datamodules.lidar_datamodule.LidarDataModule

# those two paths are specified in configs/config.yaml
lasfiles_dir: ${lasfiles_dir} 
metadata_shapefile: ${metadata_shapefile}

overfit: false  # TODO: try to access overfit_batches here
train_subtiles_by_tile: 8
batch_size: 16 # set equal to train_subtiles_by_tile when overfitting.
subtile_width_meters: 100
subtile_overlap: 0
num_workers: 0
