_target_: semantic_val.datamodules.lidar_datamodule.LidarDataModule

data_dir: ${data_dir}/lidar_toy # data_dir is specified in config.yaml
batch_size: 8
subtile_width_meters: 100
subtile_overlap: 0
num_workers: 0
train_subtiles_by_tile: 2
