_target_: semantic_val.datamodules.lidar_datamodule.LidarDataModule

data_dir: ${data_dir}/lidar_toy # data_dir is specified in config.yaml
train_subtiles_by_tile: 2
batch_size: 2 # set equal to train_subtiles_by_tile when overfitting.
subtile_width_meters: 100
subtile_overlap: 0
num_workers: 0
