_target_: semantic_val.datamodules.lidar_datamodule.LidarDataModule

# those two paths are specified in configs/config.yaml
lasfiles_dir: ${lasfiles_dir}
metadata_shapefile: ${metadata_shapefile}

train_subtiles_by_tile: 12
batch_size: 32

subsample_size: 25000
subtile_width_meters: 50
subtile_overlap: 0

limit_top_k_tiles_train: None  # if defined, use top-n clouds in terms of % building points
num_workers: 12
shuffle_train: true

