name: lidar_multiclass
channels:
  - conda-forge
  - anaconda
  - comet_ml
  - pytorch
dependencies:
  - python==3.9.*
  - pip
  # --------- numpy --------- #
  - numpy==1.20
  # --------- geo --------- #
  - pygeos
  - laspy
  - python-pdal  # useful for data preparation
  # --------- loggers --------- #
  - comet_ml
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests --------- #
  - pytest==7.1.*
  - coverage==6.3.*
  - pytest-cov==3.0.*
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  - sh # for running bash commands in some tests
  - scikit-learn # used in some callbacks
  - seaborn # used in some callbacks
  - jupyterlab # better jupyter notebooks
  - pudb # debugger
  - pip:
      - -r requirements.txt
