name: validation_module
channels:
  - conda-forge
  - anaconda
  - comet_ml
  - pytorch
dependencies:
  - python==3.9
  - pip
  # --------- geo --------- #
  - laspy
  - python-pdal
  # --------- loggers --------- #
  - comet_ml
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  - pytest # tests
  - sh # for running bash commands in some tests
  - scikit-learn # used in some callbacks
  - seaborn # used in some callbacks
  - jupyterlab # better jupyter notebooks
  - pudb # debugger
  # --------- torch --------- #
  - pytorch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - pytorch-lightning==1.3
  - cudatoolkit=11.1  # single '=' is normal here
  - pip:
      - -r requirements.txt
