# Do not scale positions to keep meter-space for neural network parameters

NullifyLowestZ:
  _target_: myria3d.pctl.transforms.transforms.NullifyLowestZ

StandardizeRGBAndIntensity:
  _target_: myria3d.pctl.transforms.transforms.StandardizeRGBAndIntensity