# Workflow name
name: "Documentation Build"

# Event that must trigger the workflow
on:
  push:         # <- trigger when we call push
    branches:
      - main  # <- but only on main branch
      - Fix-Documentation-Env

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    # Use bash instead of sh for conda activation
    defaults:
      run:
        shell: bash -l {0}
    # Task to do when launching the workflow
    steps:

      # 1. First get the repository source

      - name: "Checkout"
        uses: actions/checkout@v2

      # 2. Sphinx part : install tool and dependencies
      # See https://github.com/conda-incubator/setup-miniconda#caching-environments

      - name: Setup a conda-incubator with an empty conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
            python-version: 3.9.12
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            # For caching to work:
            use-only-tar-bz2: true
            # Environment to create and activate for next steps
            activate-environment: myria3d

      - name: Export for torch_geometric to find where cuda is.
        run: export LD_LIBRARY_PATH="/miniconda/lib/:$LD_LIBRARY_PATH" && echo ${LD_LIBRARY_PATH}

      - name: Update myria3d environment using the
        run: mamba env update -n myria3d -f environment.yml

      - name: List installed packages
        run: mamba list

      - name: "Build Sphinx Doc"
        working-directory: ./docs/
        run: make html

      # 3. Déploiement sur les Github Pages
      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages     # <- Branch where generated doc files will be commited
          FOLDER: docs/build/html/  # <- Dir where .nojekyll is created and from which to deploy github pages.
