# Characteristics of datasets obtained from SwissTopo Data
# In particular: from combining SwissSURFACE3D and SwissIMAGE10cm

# The features_names to include. 
# You must use names from LAS convention for standard channels.
# XYZ will also be included.
features_names:  
  - "intensity"
  - "return_num"
  - "num_returns"
  - "red"
  - "green"
  - "blue"
  - "composite"
  # INPUT specific parameters: change to apply on data with different scale.
  # Largest values for intensity, colors (if applicable), and return number
colors_normalization_max_value: 256  # usually 256*256 or 256 (sometimes 1?)
return_num_normalization_max_value: 7  # usually constant across datasets  # TODO: hardcode !

defaults:
  - classification: SwissSURFACE3D_all_6_classes.yaml